version: "2.4"

services:

  webfront-container:
    image: webfront
    build: .
    restart: unless-stopped
    command: -rules=./apps.json -letsencrypt_cache=./letsencrypt_cache -hostname=${HOSTNAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./apps.json:/app/apps.json
      - ./letsencrypt_cache:/app/letsencrypt_cache
    ports:
      - 443:443
      - 80:80
    environment:
     - HOSTNAME=wf.alpha.grandlyon.com
