version: "2.4"

services:

  webfront-container:
    image: webfront
    build: .
    restart: unless-stopped
    command: -apps=./apps.json -letsencrypt_cache=./letsencrypt_cache -hostname=${HOSTNAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/npernoud/apps.json:/app/apps.json
      - /home/npernoud/letsencrypt_cache:/app/letsencrypt_cache
    ports:
      - 443:443
      - 80:80
